### ISSUE TITLE
쿠폰 api 개발 

### ISSUE THREAD

**Issue by ITKOO** [winter-soft/eatda-backend#38]
베타 서비스 기간 때 사용할 쿠폰기능을 만들어야 합니다

수량은 아래와 같습니다.
이지스 40, 인엑터스 20, 이벤트 40

코드를 입력하면 장바구니에서 적용되어 
결제시 쿠폰 금액이 빠진 상태로 진행하면 됩니다

필요한 api

쿠폰 코드 입력시 수량 체크 
선착순에 포함될경우 성공 return 아닐경우 fail 
잘못된 코드일경우에도 fail 리턴

**Comment by ghdcksgml1** [comment]
쿠폰을 등록할 경우,  CouponUse 테이블에 해당 사용자, 쿠폰 외래키가 저장되고, couponUse 컬럼에는 false로 저장됨. (등록은 했지만, 사용은 안한상태)

결제확인 정보인 valid를 넣을때 couponUse_id를 같이 보내주세요. (해당 사용자가 쿠폰을 사용했는지 다시한번 체크하기위해)
주문 넣을때에도 couponUse_id를 보내주세요. (토스페이먼츠 success Response에 있습니다.)

- [ ] 쿠폰 등록 및 사용한 쿠폰 코드여부 
  - [ ] 쿠폰 등록했을때 count에서 1개 빠지는거
  - [ ] 여러 사용자가 쿠폰을 사용했을때 
  - [ ] 존재하지 않는 쿠폰코드를 입력했을때 exception
  - [ ] 만료된 쿠폰을 입력했을때 등록이 안되는지 확인
- [ ] 사용자 쿠폰조회
  - [ ] 여러개 나오는지
  - [ ] 만료된 쿠폰이 존재할때 안나오는지 체크

**Comment by ghdcksgml1** [comment]
- 쿠폰은 결제전 마이페이지 같은곳에서 등록할것 ( 결제창에서 등록은 지양 )
- 결제창에서 쿠폰은 조회해서 등록하는 방식
- 결제금액 보낼때 쿠폰 가격을 적용해서 보내지 말것 ( 백엔드에서 처리 )

## 변경사항

- 토스페이먼츠 (POST) http://api.eat-da.com/api/valid 보낼때 couponUse_id도 같이 보내주세요. (쿠폰이 적용되지 않았다면 0으로 보내기) 
- 결제완료 후 주문을 넣을때 (GET) http://api.eat-da.com/api//userOrder/{orderId}?couponUseId={value} 다음과같이 couponUseId를 RequestParam으로 보내주세요. **(couponUse_id는 토스페이먼츠 성공 후 response에서 얻을 수 있음.)**

**Comment by ITKOO** [comment]
쿠폰을 쓰지 않은 경우라면 
couponUseId 값을 아예 보내지 않으면 되나요? 
아니면 0으로 보내면 되나요?

GET http://api.eat-da.com/api/orderDetail/userOrder/8

**Comment by ghdcksgml1** [comment]
0으로 보내주심 됩니다

**Comment by ITKOO** [comment]
쿠폰 등록 api 호출 시 
쿠폰의 가격과 couponUseId를 응답에 내려주실 수 있나요?
