### ISSUE TITLE
장바구니 수량 업데이트 api 개발

### ISSUE THREAD

**Issue by ITKOO** [winter-soft/eatda-backend#41]
아래 화면에서 장바구니 수량을 변경하면 실제 수량이 업데이트 되도록 기능을 추가하고 싶습니다

order_detail_id와 수량을 보내면 업데이트 되는 api 개발 부탁드립니닷

![스크린샷 2022-11-26 오후 4 54 11](https://user-images.githubusercontent.com/31758135/204078488-fb83e6cf-a506-4241-9bd9-9c0fe057f826.png)

**Comment by ghdcksgml1** [comment]
(PUT) api.eat-da.com/api/orderDetail/quantity/{orderDetailId}

quantity 보내주세요

**Comment by ITKOO** [comment]
수량 변경은 잘됩니다~
그런데,  장바구니 조회 api에서
GET http://api.eat-da.com/api/orderDetail/
메뉴의 총액 컬럼 totalPrice 값이 바뀌지 않습니다~

확인 한번 부탁드립니다~
<img width="490" alt="스크린샷 2022-11-28 오전 4 40 10" src="https://user-images.githubusercontent.com/31758135/204156074-1b52ec25-f019-4fe4-91ef-cd91257e46e6.png">
